
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  branch = "master"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/apiextensions"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/certs"
  branch = "legacy"

[[constraint]]
  name = "github.com/giantswarm/k8scloudconfig"
  branch = "azure-operator"

[[constraint]]
  name = "github.com/giantswarm/microendpoint"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/microerror"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/microkit"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/micrologger"
  branch = "master"

[[constraint]]
  name = "github.com/giantswarm/operatorkit"
  branch = "master"
