apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: azure-operator
rules:
  - apiGroups:
      - "provider.giantswarm.io"
    resources:
      - azureconfigs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: azure-operator
subjects:
  - kind: ServiceAccount
    name: azure-operator
roleRef:
  kind: ClusterRole
  name: azure-operator
  apiGroup: rbac.authorization.k8s.io
